// FETCH ALL STUDENTS
export const FETCH_ALL_STUDENTS_REQUEST = 'students/FETCH_ALL_STUDENTS_REQUEST';
export const FETCH_ALL_STUDENTS_SUCCESS = 'students/FETCH_ALL_STUDENTS_SUCCESS';
export const FETCH_ALL_STUDENTS_FAILURE = 'students/FETCH_ALL_STUDENTS_FAILURE';
