// FETCH ALL STUDENTS
export const FETCH_ALL_STUDENTS_REQUEST = 'students/FETCH_ALL_STUDENTS_REQUEST';
export const FETCH_ALL_STUDENTS_SUCCESS = 'students/FETCH_ALL_STUDENTS_SUCCESS';
export const FETCH_ALL_STUDENTS_FAILURE = 'students/FETCH_ALL_STUDENTS_FAILURE';

// FETCH STUDENT BY ID
export const FETCH_SINGLE_STUDENT_REQUEST = 'students/FETCH_SINGLE_STUDENT_REQUEST';
export const FETCH_SINGLE_STUDENT_SUCCESS = 'students/FETCH_SINGLE_STUDENT_SUCCESS';
export const FETCH_SINGLE_STUDENT_FAILURE = 'students/FETCH_SINGLE_STUDENT_FAILURE';

// UPDATE STUDENT
export const UPDATE_STUDENT_REQUEST = 'students/UPDATE_STUDENT_REQUEST';
export const UPDATE_STUDENT_SUCCESS = 'students/UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAILURE = 'students/UPDATE_STUDENT_FAILURE';
